src/background/background.coffee, src/background/mappings.coffee, src/controllers/MonstercatController.js
Support for http://connect.monstercat.com
=> Add Monstercat Connect support

src/background/media_key_support_commands.coffee, src/content_scripts/content.coffee, src/manifest.json
Tested, working.
This resolves https://github.com/msfeldstein/chrome-media-keys/issues/42
=> Added Stop Key Functionality

src/controllers/AmazonController.js
I noticed the artist selector was cropping in really odd ways. This seems to be a lot more consistent in behavior.
=> Amazon - More reliable artist selector and High Res album art

src/controllers/SoundcloudController.js
The previous controller worked for the media keys but did not display the track, album art, or have the favorite (heart) button.
=> Updated SoundCloud Controller and switched to BasicController selectors

src/background/mappings.coffee, src/controllers/BBCRadioPopOutController.js
Tested & Working on the pop out player, but I still haven't got the embedded flash player working. This might be labeled as beta until both are supported?
=> Add BBC Radio Pop Out Support

src/controllers/BasicController.js
=> Fix missing function syntax

src/controllers/AmazonController.js, src/controllers/BasicController.js
I was able to get it done. The click function is what makes it work.
I also got the thumbs up/down working to resolve https://github.com/msfeldstein/chrome-media-keys/issues/48
=> Amazon basic

src/controllers/BasicController.js, src/controllers/BasicTemplate.js
This is really just a different take on documentation than what you added. I think it's easier to follow in terms of piecing something together (without needing to open multiple other controllers to use as examples).
This might not be the right way to go, but it's an idea :)
=> More documentation

src/controllers/NetflixController.js
The album art here is weird, but it worked (used the function from the original controller).
=> Convert Netflix to BasicController

src/controllers/BasicController.js, src/controllers/BasicTemplate.js, src/controllers/SpotifyController.js
This should work, I've tested spotify, but we could really use additional testing. I honestly don't know if there's even that many players with frames out there, so this might just be catering to spotify.
=> Frame selector

src/controllers/SpotifyController.js
Try this out, this works on the old player, and should work on the new player as well. I'm not excited about how big it is, there might be a better way to do this, but at least we can make sure this idea works.
=> Support New and Old Spotify

src/background/background.coffee, src/controllers/YoutubeController.js, src/manifest.json
This converts the current non-basic controller to a basic controller and adds support for the experimental test tube player available here https://www.youtube.com/testtube
This also adds support for thumbs up and down.
This also makes efforts to detect the availability of the previous key function. In my testing detecting when it IS available is always successful, but detecting when it IS NOT available is not always successful. The detection failure is due to the way youtube uses html5 history rather than actually loading each page you visit, thus the controller is not reinitialized when you navigate from one video to the next because the page is not actually reloaded, but rather ajax and html5 change the content of the page dynamically while preserving the controller we're loading in the …
=> Convert Youtube to BasicController

src/controllers/NoonPacificController.js
NoonPacific.com has changed significantly and the controller no longer works. These changes should update the controller for the new DOM node classes and adds support for previous track.
=> Updated NoonPacificController

src/controllers/YandexMusicController.js
Update a selector according to the site changes
=> Fix Yandex.Music

src/background/mappings.coffee, src/controllers/PocketCastsController.js
As per #85 - here's PocketCasts support. I was only able to test it on my Linux machine but here it works as expected.
Favouriting is not yet supported because there's no "Star" button in the player but only for each separate track in the playlist.
=> Added support for play.pocketcasts.com

src/controllers/PlexController.js
=> Fixed #74 (Plex Play/Pause just restarts the current album). Also fixed artwork url.

src/background/mappings.coffee, src/controllers/SubsonicController.js
Here is a SubSonic 6.0 controller, per issue #88 . :smile:
=> Add SubSonic 6.0 support.

src/controllers/MixcloudController.js
added ability to use next & prev buttons:
now they can be used to skip parts of the mix by 60 sec forwards and backwards
(similar to Overcast feature)
=> [+] improved mixcloud controller

src/background/mappings.coffee, src/content_scripts/content.coffee, src/controllers/AudiosplitterController.js
Added support for https://audiosplitter.fm/
=> Support Audiosplitter.fm

package.json, src/controllers/DeezerController.js
=> Update class targeting for Deezer controller

src/background/mappings.coffee, src/background/media_key_support_commands.coffee, src/content_scripts/content.coffee, src/manifest.json
Shortcuts added:
* Thumbs Up
* Thumbs Down
* Favorite
=> Adds additional keyboard shortcuts

src/controllers/NPROneController.js
NPR One updated their page, and it broke MediaKeys for this site. This pull request fixes the site.
=> Update NPR One controller with new format version

src/background/background.coffee, src/content_scripts/content.coffee, src/controllers/BasicController.js, src/controllers/BasicTemplate.js, src/controllers/NPROneController.js, src/controllers/PandoraController.js
This pull request makes the following changes:
* Updates codebase use modern ES6-style syntax
* Add support for multiple configurations
* Simplify method override
* Add support for Pandora's new page
The `BasicController.js` file has been refactored to use ES6-style javascript which is now supported by Chrome. This improves the code readability and maintainability.
Multiple configurations are supported now in a similar manner to previous. The configuration that is passed to the `BasicController` constructor can now be an array of configuration objects. Before the configuration is loaded, the constructor now runs the `test` method to determine if that configuration object should be used, and the first successful test is the only one used. All others are ignored (so that they can be put in …
=> New Pandora and ES6 conversion

src/content_scripts/content.coffee
Fixes #107.
1. Merged the two conditionals
2. Renamed `init` to `initIfReady`
3. Changed call to run immediately
1. In addition to trying again if `controller.init` returns false, we also want to try again if `controller` is undefined, because it should eventually always be defined. I ran into this while adding support for beta.mixcloud.com on a relatively slow machine - it wouldn't consistently have the controller code injected and executed within that first 500ms window.
2. `initIfReady` describes the functionality more accurately
3. No unnecessary repetition of the `setTimeout` call
I am not a regular coffeescript user, but I'm pretty sure much of the coffeescript in this file is not exactly idiomatic (I tried to keep the bits that I added in this PR as much in line with the rest of …
=> Simplified init routine in content.coffee

src/controllers/MusicforprogrammingController.js
I think it's nice to be able to switch to the next episode, when the current one ends, without switching to the site's tab. I also added the album art.
=> musicforprogramming.net: album art, next/prev episodes

src/controllers/MusicforprogrammingController.js
Oops, committed an untested change...
=> Fix "next episode"

src/controllers/SpotifyController.js
=> Add controller for new version of Spotify

src/controllers/VkController.js
VK has been updated to show album arts, so here's a corresponding patch.
=> Add support for album arts on VK

src/background/mappings.coffee, src/controllers/AccuRadioController.js
This adds support for AccuRadio (#116).
=> Added AccuRadio support.

src/controllers/TwitchController.js
Unfortunately Twitch has less useful CSS classes than before.
=> Fix Twitch.

src/content_scripts/content.coffee, src/controllers/LastfmController.js
This fixes Last.fm controller so it supports current version of its player.
=> Update Last.fm controller to support current player after redesign.
